# SPDX-License-Identifier: (GPL-2.0 OR BSD-2-Clause)

USER_TARGETS := dhcp_user_xdp
BPF_TARGETS :=dhcp_kern_xdp 
EXTRA_DEPS := dhcp-relay.h
#EXTRA_CFLAGS := $(if $(IPV6),-DIPV6)

LIB_DIR = ../lib

include $(LIB_DIR)/common.mk
