# SPDX-License-Identifier: (GPL-2.0 OR BSD-2-Clause)

USER_TARGETS := xdp_synproxy
BPF_TARGETS := xdp_synproxy_kern
BPF_SKEL_OBJ := xdp_synproxy_kern.o

LIB_DIR = ../lib

include $(LIB_DIR)/common.mk
