# SPDX-License-Identifier: (GPL-2.0 OR BSD-2-Clause)

USER_TARGETS    += pkt-loop-filter
BPF_TARGETS    += pkt-loop-filter.kern
EXTRA_DEPS := pkt-loop-filter.h

LIB_DIR = ../lib

include $(LIB_DIR)/common.mk
