# SPDX-License-Identifier: GPL-2.0

USER_TARGETS := ktrace01
BPF_TARGETS  := ktrace01_kern

LIB_DIR = ../lib

include $(LIB_DIR)/common.mk

# The __TARGET_ARCH_xxx is defined in lib/common.mk
# BPF_CFLAGS += -D__TARGET_ARCH_$(ARCH)
