# SPDX-License-Identifier: (GPL-2.0 OR BSD-2-Clause)

USER_TARGETS   := delay-kfunc
BPF_TARGETS    := delay-kfunc.bpf
BPF_SKEL_OBJ   := delay-kfunc.bpf.o

LIB_DIR = ../lib

include $(LIB_DIR)/common.mk

